import { useEffect,useState } from 'react';
import { getPublicConfig } from '../api';

const updated='August 30, 2026';

export function Policies({apiBase,onBack}:{apiBase:string;onBack?:()=>void}){
 const [contact,setContact]=useState({abuseContactEmail:'abuse@lyneque.com',takedownContactEmail:'abuse@lyneque.com'});
 useEffect(()=>{void getPublicConfig(apiBase).then(setContact).catch(()=>{});},[apiBase]);
 return <div className="policies-page"><article className="policies panel">{onBack&&<button onClick={onBack}>Back</button>}<h1>Lynesque policies</h1><p><strong>Effective and last updated:</strong> {updated}. These policies apply to lyneque.com, lynesque.com, and the Lynesque desktop client.</p>
  <nav className="policy-nav"><a href="#rules">Community rules</a><a href="#terms">Terms</a><a href="#privacy">Privacy</a><a href="#age">Age policy</a><a href="#takedown">Takedowns and abuse</a></nav>
  <section id="rules"><h2>Community rules</h2><p>Lynesque is for creative videos, discussion, and remixing—not for harming, exploiting, or terrorizing people. Do not upload, post, link to, solicit, or encourage:</p><ul>
   <li>sexual exploitation of minors, grooming, or any sexual content involving a person under 18;</li>
   <li>pornography, explicit sexual acts, fetish content focused on genitals, or real or photorealistic nudity;</li>
   <li>gore, dismemberment, graphic real-world injury, cruelty, or content primarily intended to shock or traumatize;</li>
   <li>hate speech, dehumanization, targeted slurs, praise of hate groups, or harassment based on a protected trait;</li>
   <li>credible threats, targeted harassment, stalking, doxxing, non-consensual intimate material, or instructions encouraging self-harm;</li>
   <li>malware, credential theft, spam, ban evasion, impersonation, payment fraud, or attempts to bypass moderation and safety systems;</li>
   <li>content that violates another person’s copyright, privacy, publicity, or other legal rights.</li>
  </ul><h3>Mature but permitted content</h3><p>Profanity, mildly sexual or suggestive material that is not pornographic, and stylized or non-graphic violence may be allowed. Uploaders must apply the <strong>Mature</strong> tag whenever a reasonable viewer may not want that material shown without warning. The Mature tag never makes prohibited pornography, realistic nudity, gore, exploitation, or hate speech permissible.</p><p>Moderators may warn, hide, remove, restrict, suspend, or ban accounts and content when reasonably needed to protect users, comply with law or service-provider rules, stop disruption, or address conduct not anticipated word-for-word here. Decisions should be made in good faith, proportionately, and documented in moderation logs.</p></section>
  <section id="terms"><h2>Terms of use</h2><p>By creating an account or using Lynesque, you agree to these policies and confirm that you meet the minimum age. You retain ownership of your content. You grant Lynesque a non-exclusive license to store, reproduce, compress, display, and deliver it as needed to operate, moderate, back up, and improve the service. Public assets may be reused through Lynesque’s creator library; assets marked Private are excluded from that library and from ShitTok’s asset selection.</p><p>You are responsible for your account, password, uploads, and activity. Do not interfere with the service or access another account. Lynesque may change, suspend, or discontinue features and may remove content or accounts under these rules. The service is provided as available without a guarantee that it will be uninterrupted or error-free. Nothing in these terms limits rights that cannot legally be waived.</p></section>
  <section id="privacy"><h2>Privacy policy</h2><p>Lynesque stores account identifiers, password hashes, optional verified email addresses, MFA state, sessions, preferences, follows, reactions, views, posts, comments, reports, moderation records, Patreon entitlement identifiers, and uploaded media. It processes connection IP addresses in memory for anti-abuse limits, while Cloudflare and other infrastructure providers may retain their own security logs. Passwords, MFA codes, email-verification tokens, and session tokens are stored only as cryptographic hashes where applicable.</p><p>Data is used to operate accounts and feeds, deliver email and Patreon features, enforce rules, investigate abuse, secure the service, and restore failures. Cloudflare handles edge traffic; Resend handles verification and MFA email when configured; Patreon handles membership linking; the configured image-safety provider may receive a compressed moderation copy of uploaded images; and the configured encrypted backup provider stores encrypted backup data. Lynesque does not sell personal information.</p><p>Resolved reports are retained for up to seven days, administrative action logs for up to 21 days, and encrypted backup snapshots according to the host’s backup-retention schedule. Security, legal, or abuse evidence may be kept longer when reasonably necessary. Account deletion is not yet self-service; request deletion or data access using the abuse address below. Some data may remain temporarily in encrypted backups until those snapshots expire.</p></section>
  <section id="age"><h2>Minimum-age policy</h2><p>You must be at least <strong>16</strong> to use Lynesque. Mature-tagged content is hidden by default and may be enabled only after confirming you are at least <strong>18</strong>. If Lynesque learns that an account is under the minimum age, the account and associated personal data may be removed. A parent or guardian can report an underage account using the abuse contact.</p></section>
  <section id="takedown"><h2>Takedowns, copyright, and abuse reports</h2><p>Use the in-app report option for a user, video, asset, comment, reply, or Postboard post. For urgent safety issues, account/data requests, or reports you cannot submit in-app, email <a href={`mailto:${contact.abuseContactEmail}`}>{contact.abuseContactEmail}</a>. For copyright or other legal takedown requests, email <a href={`mailto:${contact.takedownContactEmail}`}>{contact.takedownContactEmail}</a>.</p><p>Include your name and contact information, the Lynesque username or human-readable video reference, the exact material and location, the reason for the request, and—when alleging rights infringement—an explanation of the right you own or represent and a good-faith statement that the use is unauthorized. Do not send knowingly false reports. Moderators may ask for more information, preserve relevant evidence, remove or restrict the material, suspend an account, or deny the request. Appeals can be sent to the same address with the report details and why the decision should be reconsidered.</p></section>
 </article></div>;
}
