import { useEffect, useRef, useState } from 'react';
import { addBoardComment, adminDeleteBoardComment, adminDeleteBoardPost, clearBoardNotifications, createBoardPost, getBoardNotifications, getBoardPosts, markBoardNotificationsRead, mediaUrl, toggleBoardCommentReaction, toggleBoardReaction } from '../api';
import type { AssetRecord, BoardPost, Notification, User } from '../types';
import { AssetLibrary } from './AssetLibrary';
import { AdminMenu } from './AdminMenu';
import { UserAvatar, UserName } from './UserIdentity';

const ago = (time: string) => new Date(time).toLocaleString();
function linked(text: string, onHash: (tag: string) => void) {
  return text.split(/(#[a-zA-Z0-9_-]+)/g).map((part, index) => part.startsWith('#') ? <button className="text-link" key={index} onClick={() => onHash(part)}>{part}</button> : part);
}
const boardMessages:Partial<Record<Notification['kind'],string>>={board_like:'liked your Postboard post',board_dislike:'disliked your Postboard post',board_comment:'commented on your Postboard post',board_mention:'mentioned you in a Postboard post',board_comment_mention:'mentioned you in a Postboard reply',board_comment_like:'liked your Postboard reply',board_comment_dislike:'disliked your Postboard reply',follow_board:'made a new Postboard post',following_board_comment:'commented on Postboard'};
function BoardItem({ post, apiBase, token, user, onPost, onDelete, onHash, onProfile }: { post: BoardPost; apiBase:string; token:string; user:User; onPost:(post:BoardPost)=>void; onDelete:()=>void; onHash:(tag:string)=>void; onProfile:(id:string)=>void }) {
  const [comment, setComment] = useState(''); const [sticker, setSticker] = useState<AssetRecord>(); const [stickers, setStickers] = useState(false); const [open, setOpen] = useState(false);
  const reload = async()=>{const next=(await getBoardPosts(apiBase,token)).posts.find((item)=>item.id===post.id);if(next)onPost(next);};
  const send = async () => { if (!comment.trim() && !sticker) return; await addBoardComment(apiBase,token,post.id,comment,sticker?.id); setComment('');setSticker(undefined);setStickers(false); onPost((await getBoardPosts(apiBase,token)).posts.find((item)=>item.id===post.id)!); };
  return <article id={`board-${post.id}`} className="board-post panel"><header><button className="board-author" onClick={()=>onProfile(post.author.id)}><UserAvatar apiBase={apiBase} user={post.author} small/><strong><UserName user={post.author}/></strong></button><div className="post-head-actions"><time>{ago(post.createdAt)}</time>{user.isAdmin&&<AdminMenu label="Moderate Postboard post" onDelete={async()=>{if(!window.confirm('Delete this Postboard post?'))return;const reason=window.prompt('Reason shown to the creator and saved in the admin log:','Removed directly by an admin.');if(reason===null)return;await adminDeleteBoardPost(apiBase,token,post.id,reason);onDelete();}}/>}</div></header><div className="board-text">{linked(post.text,onHash)}</div>{post.sticker && <img className="board-sticker" src={mediaUrl(apiBase,post.sticker.id)} />}
    <div className="post-actions"><button className={post.likedByViewer?'liked':''} onClick={async()=>onPost((await toggleBoardReaction(apiBase,token,post.id,'like')).post)}>▲</button><strong>{post.likeCount}</strong><button className={post.dislikedByViewer?'disliked':''} onClick={async()=>onPost((await toggleBoardReaction(apiBase,token,post.id,'dislike')).post)}>▼</button><button onClick={()=>setOpen(!open)}>Comments ({post.comments.length})</button></div>
    {open && <div className="board-comments">{post.comments.map((entry)=><div className="comment" key={entry.id}><UserAvatar apiBase={apiBase} user={entry.user} small/><button className="inline-user" onClick={()=>onProfile(entry.user?.id||entry.userId)}><strong><UserName user={entry.user} fallbackId={entry.userId}/></strong></button><span>{linked(entry.text,onHash)}</span>{entry.sticker&&<img className="comment-sticker" src={mediaUrl(apiBase,entry.sticker.id)}/>}<small>{ago(entry.createdAt)}</small><button className={entry.likedByViewer?'liked':''} onClick={async()=>onPost((await toggleBoardCommentReaction(apiBase,token,post.id,entry.id,'like')).post)}>▲</button><strong className="reply-score">{entry.likeCount}</strong><button className={entry.dislikedByViewer?'disliked':''} onClick={async()=>onPost((await toggleBoardCommentReaction(apiBase,token,post.id,entry.id,'dislike')).post)}>▼</button>{user.isAdmin&&<AdminMenu label="Moderate Postboard reply" onDelete={async()=>{if(!window.confirm('Delete this reply?'))return;const reason=window.prompt('Reason shown to the commenter and saved in the admin log:','Removed directly by an admin.');if(reason===null)return;await adminDeleteBoardComment(apiBase,token,post.id,entry.id,reason);await reload();}}/>}</div>)}
      <div className="comment-box"><input value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Reply… @mentions work"/><button onClick={()=>setStickers(!stickers)}>Sticker</button>{sticker&&<img className="comment-sticker" src={mediaUrl(apiBase,sticker.id)}/>}<button onClick={send}>Reply</button></div>{stickers&&<AssetLibrary apiBase={apiBase} token={token} isAdmin={user.isAdmin} sections={['image','gif']} title="Stickers" onSelect={(asset)=>{setSticker(asset);setStickers(false);}}/>}</div>}
  </article>;
}
export function Postboard({apiBase,token,user,onSearch,onUnreadCount,onProfile}:{apiBase:string;token:string;user:User;onSearch:(tag:string)=>void;onUnreadCount:(count:number)=>void;onProfile:(id:string)=>void}) {
 const [posts,setPosts]=useState<BoardPost[]>([]);const [text,setText]=useState('');const [sticker,setSticker]=useState<AssetRecord>();const [library,setLibrary]=useState(false);const [notes,setNotes]=useState<Notification[]>([]);const [notesOpen,setNotesOpen]=useState(true);
 const highlighted=useRef(new Set<string>());const refresh=async()=>{const [p,n]=await Promise.all([getBoardPosts(apiBase,token),getBoardNotifications(apiBase,token)]);setPosts(p.posts);for(const item of n.notifications)if(!item.readAt)highlighted.current.add(item.id);setNotes(n.notifications);if(notesOpen&&n.unreadCount){await markBoardNotificationsRead(apiBase,token);onUnreadCount(0);}else onUnreadCount(n.unreadCount);}; useEffect(()=>{refresh();const timer=window.setInterval(refresh,5000);return()=>window.clearInterval(timer);},[apiBase,token,notesOpen]);
 const submit=async()=>{if(!text.trim()&&!sticker)return;await createBoardPost(apiBase,token,text,sticker?.id);setText('');setSticker(undefined);setLibrary(false);refresh();};
 const clearNotes=async()=>{if(!notes.length||!window.confirm('Clear all Postboard notifications? This cannot be undone.'))return;await clearBoardNotifications(apiBase,token);highlighted.current.clear();setNotes([]);onUnreadCount(0);};
 const update=(next:BoardPost)=>setPosts((items)=>items.map((item)=>item.id===next.id?next:item));
 return <div className={`postboard-page ${notesOpen?'with-board-notifications':''}`}>{notesOpen?<aside className="board-notifications panel"><header><h2>Postboard notifications</h2><div><button onClick={clearNotes} disabled={!notes.length}>Clear</button><button onClick={()=>{setNotesOpen(false);highlighted.current.clear();}}>Hide</button></div></header><div className="notification-list">{notes.map((note)=><div className={highlighted.current.has(note.id)?'notification notification-new':'notification'} key={note.id}><button className="notification-avatar" onClick={()=>onProfile(note.actor?.id||note.actorId)}><UserAvatar apiBase={apiBase} user={note.actor} small/></button><button className="notification-body" onClick={()=>{if(note.boardPostId)document.getElementById(`board-${note.boardPostId}`)?.scrollIntoView({behavior:'smooth'});else onProfile(note.actor?.id||note.actorId);}}><span>{note.message||<><strong><UserName user={note.actor} fallbackId={note.actorId}/></strong> {boardMessages[note.kind]||note.kind.replaceAll('_',' ')}</>}</span><time>{ago(note.createdAt)}</time></button></div>)}</div></aside>:<button className="show-board-notifications" onClick={()=>setNotesOpen(true)}>Show Postboard notifications</button>}<div className="board-main"><section className="board-compose panel"><textarea value={text} onChange={(e)=>setText(e.target.value)} maxLength={1000} placeholder="Say something terrible… #hashtags and @people work"/>{sticker&&<img className="board-sticker" src={mediaUrl(apiBase,sticker.id)}/>}<div><button onClick={()=>setLibrary(!library)}>Sticker</button><button className="primary" onClick={submit}>Post</button></div>{library&&<AssetLibrary apiBase={apiBase} token={token} isAdmin={user.isAdmin} sections={['image','gif']} title="Stickers" onSelect={(asset)=>{setSticker(asset);setLibrary(false);}}/>}</section>{posts.map((post)=><BoardItem key={post.id} post={post} apiBase={apiBase} token={token} user={user} onPost={update} onDelete={()=>setPosts((items)=>items.filter((item)=>item.id!==post.id))} onHash={onSearch} onProfile={onProfile}/>)}</div></div>;
}
