import { useEffect, useRef, useState } from 'react';
import { addBoardComment, adminDeleteBoardComment, adminDeleteBoardPost, clearBoardNotifications, createBoardPost, createReport, deleteBoardComment, deleteBoardPost, getBoardComments, getBoardNotifications, getBoardPosts, markBoardNotificationsRead, mediaUrl, toggleBoardCommentReaction, toggleBoardReaction } from '../api';
import type { AssetRecord, BoardPost, Comment, Notification, User } from '../types';
import { AssetLibrary } from './AssetLibrary';
import { AdminMenu } from './AdminMenu';
import { UserAvatar, UserName } from './UserIdentity';

const ago=(time:string)=>new Date(time).toLocaleString();
function linked(text:string,onHash:(tag:string)=>void){return text.split(/(#[a-zA-Z0-9_-]+)/g).map((part,index)=>part.startsWith('#')?<button className="text-link" key={index} onClick={()=>onHash(part)}>{part}</button>:part);}
const boardMessages:Partial<Record<Notification['kind'],string>>={board_like:'liked your Postboard post',board_dislike:'disliked your Postboard post',board_comment:'commented on your Postboard post',board_mention:'mentioned you in a Postboard post',board_comment_mention:'mentioned you in a Postboard reply',board_comment_like:'liked your Postboard reply',board_comment_dislike:'disliked your Postboard reply',follow_board:'made a new Postboard post',following_board_comment:'commented on Postboard'};
async function quickReport(apiBase:string,token:string,input:Parameters<typeof createReport>[2]){const reason=window.prompt('Why are you reporting this?');if(reason?.trim())await createReport(apiBase,token,{...input,reason});}

function BoardItem({post,apiBase,token,user,onPost,onDelete,onHash,onProfile}:{post:BoardPost;apiBase:string;token:string;user:User;onPost:(post:BoardPost)=>void;onDelete:()=>void;onHash:(tag:string)=>void;onProfile:(id:string)=>void}){
 const [comment,setComment]=useState('');const [sticker,setSticker]=useState<AssetRecord>();const [stickers,setStickers]=useState(false);const [open,setOpen]=useState(false);const [comments,setComments]=useState<Comment[]>(post.comments);const [commentsHasMore,setCommentsHasMore]=useState(post.commentsHasMore);
 useEffect(()=>{setComments(post.comments);setCommentsHasMore(post.commentsHasMore);},[post.id,post.comments]);
 const reloadComments=async()=>{const result=await getBoardComments(apiBase,token,post.id,0,Math.max(16,comments.length));setComments(result.comments);setCommentsHasMore(result.hasMore);};
 const send=async()=>{if(!comment.trim()&&!sticker)return;await addBoardComment(apiBase,token,post.id,comment,sticker?.id);setComment('');setSticker(undefined);setStickers(false);await reloadComments();};
 const deletePostAction=async()=>{if(!window.confirm('Delete this Postboard post?'))return;if(user.isAdmin){const reason=window.prompt('Reason shown to the creator and saved in the admin log:','Removed directly by an admin.');if(reason===null)return;await adminDeleteBoardPost(apiBase,token,post.id,reason);}else await deleteBoardPost(apiBase,token,post.id);onDelete();};
 return <article id={`board-${post.id}`} className="board-post panel"><header><button className="board-author" onClick={()=>onProfile(post.author.id)}><UserAvatar apiBase={apiBase} user={post.author} small/><strong><UserName user={post.author}/></strong></button><div className="post-head-actions"><time>{ago(post.createdAt)}</time><AdminMenu label="Postboard post options" onDelete={user.isAdmin||post.authorId===user.id?deletePostAction:undefined} onReport={!user.isAdmin&&post.authorId!==user.id?()=>quickReport(apiBase,token,{targetType:'board_post',boardPostId:post.id,reason:''}):undefined}/></div></header>
  <div className="board-text">{linked(post.text,onHash)}</div>{post.sticker&&<img className="board-sticker" src={mediaUrl(apiBase,post.sticker.id)} alt="Sticker"/>}
  <div className="post-actions"><button className={post.likedByViewer?'liked':''} onClick={async()=>onPost((await toggleBoardReaction(apiBase,token,post.id,'like')).post)}>▲</button><strong>{post.likeCount}</strong><button className={post.dislikedByViewer?'disliked':''} onClick={async()=>onPost((await toggleBoardReaction(apiBase,token,post.id,'dislike')).post)}>▼</button><button onClick={()=>setOpen(!open)}>Comments ({post.commentsTotal})</button></div>
  {open&&<div className="board-comments">{comments.map((entry)=><div className="comment" key={entry.id}><div className="board-comment-author"><UserAvatar apiBase={apiBase} user={entry.user} small/><button className="inline-user" onClick={()=>onProfile(entry.user?.id||entry.userId)}><strong><UserName compact user={entry.user} fallbackId={entry.userId}/></strong></button></div><span className="board-comment-text">{linked(entry.text,onHash)}</span>{entry.sticker&&<img className="comment-sticker" src={mediaUrl(apiBase,entry.sticker.id)} alt="Sticker"/>}<small>{ago(entry.createdAt)}</small><button className={entry.likedByViewer?'liked':''} onClick={async()=>{const next=(await toggleBoardCommentReaction(apiBase,token,post.id,entry.id,'like')).post;onPost(next);setComments(next.comments);}}>▲</button><strong className="reply-score">{entry.likeCount}</strong><button className={entry.dislikedByViewer?'disliked':''} onClick={async()=>{const next=(await toggleBoardCommentReaction(apiBase,token,post.id,entry.id,'dislike')).post;onPost(next);setComments(next.comments);}}>▼</button><AdminMenu label="Reply options" onDelete={user.isAdmin||entry.userId===user.id?async()=>{if(!window.confirm('Delete this reply?'))return;if(user.isAdmin){const reason=window.prompt('Reason shown to the commenter and saved in the admin log:','Removed directly by an admin.');if(reason===null)return;await adminDeleteBoardComment(apiBase,token,post.id,entry.id,reason);}else await deleteBoardComment(apiBase,token,post.id,entry.id);await reloadComments();}:undefined} onReport={!user.isAdmin&&entry.userId!==user.id?()=>quickReport(apiBase,token,{targetType:'board_comment',boardPostId:post.id,commentId:entry.id,reason:''}):undefined}/></div>)}
   {commentsHasMore&&<button className="load-more" onClick={async()=>{const result=await getBoardComments(apiBase,token,post.id,comments.length,16);setComments((items)=>[...items,...result.comments]);setCommentsHasMore(result.hasMore);}}>Load more replies</button>}
   <div className="comment-box"><input value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Reply… @mentions work"/><button onClick={()=>setStickers(!stickers)}>Sticker</button>{sticker&&<img className="comment-sticker" src={mediaUrl(apiBase,sticker.id)} alt=""/>}<button onClick={send}>Reply</button></div>{stickers&&<AssetLibrary apiBase={apiBase} token={token} viewer={user} isAdmin={user.isAdmin} sections={['image','gif']} title="Stickers" onSelect={(asset)=>{setSticker(asset);setStickers(false);}}/>}</div>}
 </article>;
}

export function Postboard({apiBase,token,user,onSearch,onUnreadCount,onProfile}:{apiBase:string;token:string;user:User;onSearch:(tag:string)=>void;onUnreadCount:(count:number)=>void;onProfile:(id:string)=>void}){
 const [posts,setPosts]=useState<BoardPost[]>([]);const [postsHasMore,setPostsHasMore]=useState(false);const [text,setText]=useState('');const [sticker,setSticker]=useState<AssetRecord>();const [library,setLibrary]=useState(false);const [notes,setNotes]=useState<Notification[]>([]);const [notesHasMore,setNotesHasMore]=useState(false);const [notesOpen,setNotesOpen]=useState(true);const [status,setStatus]=useState('');const highlighted=useRef(new Set<string>());
 const refresh=async()=>{try{const [p,n]=await Promise.all([getBoardPosts(apiBase,token,0,20),getBoardNotifications(apiBase,token,0,30)]);setPosts((items)=>{const merged=[...p.posts,...items.filter((item)=>!p.posts.some((fresh)=>fresh.id===item.id))];setPostsHasMore(merged.length<p.total);return merged;});for(const item of n.notifications)if(!item.readAt)highlighted.current.add(item.id);setNotes((items)=>{const merged=[...n.notifications,...items.filter((item)=>!n.notifications.some((fresh)=>fresh.id===item.id))];setNotesHasMore(merged.length<n.total);return merged;});if(notesOpen&&n.unreadCount){await markBoardNotificationsRead(apiBase,token);onUnreadCount(0);}else onUnreadCount(n.unreadCount);}catch(error){setStatus(error instanceof Error?error.message:'Postboard failed.');}};
 useEffect(()=>{setPosts([]);setNotes([]);void refresh();const timer=window.setInterval(refresh,5000);return()=>window.clearInterval(timer);},[apiBase,token,notesOpen]);
 const submit=async()=>{if(user.accountStatus==='unverified')return setStatus('Unverified accounts cannot publish on Postboard.');if(!text.trim()&&!sticker)return;try{await createBoardPost(apiBase,token,text,sticker?.id);setText('');setSticker(undefined);setLibrary(false);await refresh();}catch(error){setStatus(error instanceof Error?error.message:'Post failed.');}};
 const clearNotes=async()=>{if(!notes.length||!window.confirm('Clear all Postboard notifications? This cannot be undone.'))return;await clearBoardNotifications(apiBase,token);highlighted.current.clear();setNotes([]);setNotesHasMore(false);onUnreadCount(0);};const update=(next:BoardPost)=>setPosts((items)=>items.map((item)=>item.id===next.id?next:item));
 const loadOlderNotes=async()=>{if(!notesHasMore)return;const result=await getBoardNotifications(apiBase,token,notes.length,30);setNotes((items)=>[...items,...result.notifications]);setNotesHasMore(result.hasMore);};
 return <div className={`postboard-page ${notesOpen?'with-board-notifications':''}`}>{notesOpen?<aside className="board-notifications panel"><header><h2>Postboard notifications</h2><div><button onClick={clearNotes} disabled={!notes.length}>Clear</button><button onClick={()=>{setNotesOpen(false);highlighted.current.clear();}}>Hide</button></div></header><div className="notification-list" onScroll={(event)=>{const node=event.currentTarget;if(node.scrollTop+node.clientHeight>=node.scrollHeight-30)void loadOlderNotes();}}>{notes.map((note)=><div className={highlighted.current.has(note.id)?'notification notification-new':'notification'} key={note.id}><button className="notification-avatar" onClick={()=>onProfile(note.actor?.id||note.actorId)}><UserAvatar apiBase={apiBase} user={note.actor} small/></button><button className="notification-body" onClick={()=>{if(note.boardPostId)document.getElementById(`board-${note.boardPostId}`)?.scrollIntoView({behavior:'smooth'});else onProfile(note.actor?.id||note.actorId);}}><span>{note.message||<><strong><UserName compact user={note.actor} fallbackId={note.actorId}/></strong> {boardMessages[note.kind]||note.kind.replaceAll('_',' ')}</>}</span><time>{ago(note.createdAt)}</time></button></div>)}</div>{notesHasMore&&<button className="load-more" onClick={loadOlderNotes}>Load older</button>}</aside>:<button className="show-board-notifications" onClick={()=>setNotesOpen(true)}>Show Postboard notifications</button>}
 <div className="board-main"><section className="board-compose panel">{user.accountStatus==='unverified'&&<div className="review-notice">Unverified accounts can reply and react, but cannot publish new Postboard posts.</div>}<textarea disabled={user.accountStatus==='unverified'} value={text} onChange={(e)=>setText(e.target.value)} maxLength={1000} placeholder="Say something terrible… #hashtags and @people work"/>{sticker&&<img className="board-sticker" src={mediaUrl(apiBase,sticker.id)} alt=""/>}<div><button disabled={user.accountStatus==='unverified'} onClick={()=>setLibrary(!library)}>Sticker</button><button disabled={user.accountStatus==='unverified'} className="primary" onClick={submit}>Post</button></div>{library&&<AssetLibrary apiBase={apiBase} token={token} viewer={user} isAdmin={user.isAdmin} sections={['image','gif']} title="Stickers" onSelect={(asset)=>{setSticker(asset);setLibrary(false);}}/>}</section>{status&&<div className="status">{status}</div>}{posts.map((post)=><BoardItem key={post.id} post={post} apiBase={apiBase} token={token} user={user} onPost={update} onDelete={()=>setPosts((items)=>items.filter((item)=>item.id!==post.id))} onHash={onSearch} onProfile={onProfile}/>)}{postsHasMore&&<button className="load-more panel" onClick={async()=>{const result=await getBoardPosts(apiBase,token,posts.length,20);setPosts((items)=>[...items,...result.posts]);setPostsHasMore(result.hasMore);}}>Load more posts</button>}</div></div>;
}
