import { useEffect, useState } from 'react';
import { addBoardComment, createBoardPost, getBoardNotifications, getBoardPosts, markBoardNotificationsRead, mediaUrl, toggleBoardCommentReaction, toggleBoardReaction } from '../api';
import type { AssetRecord, BoardPost, Notification, User } from '../types';
import { AssetLibrary } from './AssetLibrary';

const ago = (time: string) => new Date(time).toLocaleString();
function linked(text: string, onHash: (tag: string) => void) {
  return text.split(/(#[a-zA-Z0-9_-]+)/g).map((part, index) => part.startsWith('#') ? <button className="text-link" key={index} onClick={() => onHash(part)}>{part}</button> : part);
}
function BoardItem({ post, apiBase, token, onPost, onHash }: { post: BoardPost; apiBase:string; token:string; onPost:(post:BoardPost)=>void; onHash:(tag:string)=>void }) {
  const [comment, setComment] = useState(''); const [sticker, setSticker] = useState<AssetRecord>(); const [stickers, setStickers] = useState(false); const [open, setOpen] = useState(false);
  const send = async () => { if (!comment.trim() && !sticker) return; await addBoardComment(apiBase,token,post.id,comment,sticker?.id); setComment('');setSticker(undefined);setStickers(false); onPost((await getBoardPosts(apiBase,token)).posts.find((item)=>item.id===post.id)!); };
  return <article className="board-post panel"><header><strong>@{post.author.displayName}</strong><time>{ago(post.createdAt)}</time></header><div className="board-text">{linked(post.text,onHash)}</div>{post.sticker && <img className="board-sticker" src={mediaUrl(apiBase,post.sticker.id)} />}
    <div className="post-actions"><button className={post.likedByViewer?'liked':''} onClick={async()=>onPost((await toggleBoardReaction(apiBase,token,post.id,'like')).post)}>▲</button><strong>{post.likeCount}</strong><button className={post.dislikedByViewer?'disliked':''} onClick={async()=>onPost((await toggleBoardReaction(apiBase,token,post.id,'dislike')).post)}>▼</button><button onClick={()=>setOpen(!open)}>Comments ({post.comments.length})</button></div>
    {open && <div className="board-comments">{post.comments.map((entry)=><div className="comment" key={entry.id}><strong>@{entry.user?.displayName}</strong><span>{linked(entry.text,onHash)}</span>{entry.sticker&&<img className="comment-sticker" src={mediaUrl(apiBase,entry.sticker.id)}/>}<small>{ago(entry.createdAt)}</small><button className={entry.likedByViewer?'liked':''} onClick={async()=>onPost((await toggleBoardCommentReaction(apiBase,token,post.id,entry.id,'like')).post)}>▲ {entry.likeCount}</button><button className={entry.dislikedByViewer?'disliked':''} onClick={async()=>onPost((await toggleBoardCommentReaction(apiBase,token,post.id,entry.id,'dislike')).post)}>▼</button></div>)}
      <div className="comment-box"><input value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Reply… @mentions work"/><button onClick={()=>setStickers(!stickers)}>Sticker</button>{sticker&&<img className="comment-sticker" src={mediaUrl(apiBase,sticker.id)}/>}<button onClick={send}>Reply</button></div>{stickers&&<AssetLibrary apiBase={apiBase} token={token} sections={['image','gif']} title="Stickers" onSelect={(asset)=>{setSticker(asset);setStickers(false);}}/>}</div>}
  </article>;
}
export function Postboard({apiBase,token,user,onSearch}:{apiBase:string;token:string;user:User;onSearch:(tag:string)=>void}) {
 const [posts,setPosts]=useState<BoardPost[]>([]);const [text,setText]=useState('');const [sticker,setSticker]=useState<AssetRecord>();const [library,setLibrary]=useState(false);const [notes,setNotes]=useState<Notification[]>([]);const [notesOpen,setNotesOpen]=useState(true);
 const refresh=async()=>{const [p,n]=await Promise.all([getBoardPosts(apiBase,token),getBoardNotifications(apiBase,token)]);setPosts(p.posts);setNotes(n.notifications);}; useEffect(()=>{refresh();},[apiBase,token]);
 const submit=async()=>{if(!text.trim()&&!sticker)return;await createBoardPost(apiBase,token,text,sticker?.id);setText('');setSticker(undefined);setLibrary(false);refresh();};
 const update=(next:BoardPost)=>setPosts((items)=>items.map((item)=>item.id===next.id?next:item));
 return <div className="postboard-page"><aside className="board-notifications panel">{notesOpen?<><header><h2>Postboard notifications</h2><button onClick={()=>setNotesOpen(false)}>Hide</button></header>{notes.map((note)=><div className={!note.readAt?'notification notification-new':'notification'} key={note.id}>@{note.actor?.displayName||note.actorId} {note.kind.replaceAll('_',' ')}</div>)}<button onClick={async()=>{await markBoardNotificationsRead(apiBase,token);refresh();}}>Mark seen</button></>:<button onClick={()=>setNotesOpen(true)}>Show Postboard notifications</button>}</aside><main className="board-main"><section className="board-compose panel"><textarea value={text} onChange={(e)=>setText(e.target.value)} maxLength={1000} placeholder="Say something terrible… #hashtags and @people work"/>{sticker&&<img className="board-sticker" src={mediaUrl(apiBase,sticker.id)}/>}<div><button onClick={()=>setLibrary(!library)}>Sticker</button><button className="primary" onClick={submit}>Post</button></div>{library&&<AssetLibrary apiBase={apiBase} token={token} sections={['image','gif']} title="Stickers" onSelect={(asset)=>{setSticker(asset);setLibrary(false);}}/>}</section>{posts.map((post)=><BoardItem key={post.id} post={post} apiBase={apiBase} token={token} onPost={update} onHash={onSearch}/>)}</main></div>;
}
