import { useState } from 'react';
import { createReport, mediaUrl } from '../api';
import type { AssetRecord, User } from '../types';
import { AssetLibrary } from './AssetLibrary';

export function Reports({apiBase,token,user,onBack}:{apiBase:string;token:string;user:User;onBack:()=>void}){
 const [type,setType]=useState<'user'|'asset'>('user');const [username,setUsername]=useState('');const [asset,setAsset]=useState<AssetRecord>();const [reason,setReason]=useState('');const [status,setStatus]=useState('');
 const submit=async()=>{try{setStatus('Sending report…');await createReport(apiBase,token,{targetType:type,username:type==='user'?username:undefined,assetId:type==='asset'?asset?.id:undefined,reason});setUsername('');setAsset(undefined);setReason('');setStatus('Report sent to the admins.');}catch(error){setStatus(error instanceof Error?error.message:'Report failed.');}};
 return <div className="settings-page"><section className="settings-panel panel"><div className="settings-head"><h1>Reports</h1><button onClick={onBack}>Back to settings</button></div>{user.isAdmin?<p>Admins cannot make reports. Use the Admin page instead.</p>:<><div className="segmented"><button className={type==='user'?'active':''} onClick={()=>setType('user')}>Report user</button><button className={type==='asset'?'active':''} onClick={()=>setType('asset')}>Report asset</button></div>{type==='user'?<label>User<input value={username} onChange={(e)=>setUsername(e.target.value)} placeholder="@username"/></label>:<>{asset&&<div className="reported-asset"><img src={mediaUrl(apiBase,asset.id)}/><span>{asset.originalName}</span><button onClick={()=>setAsset(undefined)}>Remove</button></div>}<AssetLibrary apiBase={apiBase} token={token} sections={['image','gif','video','audio']} title="Choose an asset to report" selectedId={asset?.id} onSelect={setAsset}/></>}<label>Reason<textarea value={reason} onChange={(e)=>setReason(e.target.value)} maxLength={1000}/></label><button className="primary" disabled={!reason.trim()||(type==='user'?!username.trim():!asset)} onClick={submit}>Submit report</button></>}{status&&<div className="status">{status}</div>}</section></div>;
}
