import { useEffect, useState } from 'react';
import { getNotificationSettings, setNotificationSettings } from '../api';
import type { NotificationKind, NotificationPreferences, User } from '../types';
import { Reports } from './Reports';

const labels:Record<NotificationKind,string>={post_like:'Someone likes your video',post_dislike:'Someone dislikes your video',follow:'Someone follows you',unfollow:'Someone unfollows you',comment_mention:'You are mentioned in a video comment',video_mention:'You are mentioned in video text or its title',comment:'Someone comments on your video',comment_like:'Someone likes your video comment',comment_dislike:'Someone dislikes your video comment',board_like:'Someone likes your Postboard post',board_dislike:'Someone dislikes your Postboard post',board_comment:'Someone comments on your Postboard post',board_mention:'You are mentioned in a Postboard post',board_comment_mention:'You are mentioned in a Postboard reply',board_comment_like:'Someone likes your Postboard reply',board_comment_dislike:'Someone dislikes your Postboard reply',follow_video:'Someone you follow posts a video',follow_board:'Someone you follow makes a Postboard post',following_video_comment:'Someone you follow comments on a video',following_board_comment:'Someone you follow comments on Postboard',asset_removed:'Your asset is taken down',content_removed:'Your content is taken down',admin_changed:'Your admin status changes',report_resolved:'Your report is accepted or denied',admin_rate_limited:'An admin is automatically rate-limited',automatic_suspension:'A user is automatically suspended by asset safety'};
export function Settings({apiBase,token,user}:{apiBase:string;token:string;user:User}){
 const [preferences,setPreferences]=useState<NotificationPreferences>();const [scale,setScale]=useState(Number(localStorage.getItem('lynesque-ui-scale')||1));const [arrowSide,setArrowSide]=useState(localStorage.getItem('lynesque-arrow-side')==='right'?'right':'left');const [reports,setReports]=useState(false);const [status,setStatus]=useState('');
 useEffect(()=>{getNotificationSettings(apiBase,token).then((r)=>setPreferences(r.preferences)).catch((e)=>setStatus(e.message));},[apiBase,token]);
 if(reports)return <Reports apiBase={apiBase} token={token} user={user} onBack={()=>setReports(false)}/>;
 const save=async()=>{if(!preferences)return;try{setPreferences((await setNotificationSettings(apiBase,token,preferences)).preferences);setStatus('Settings saved.');}catch(e){setStatus(e instanceof Error?e.message:'Save failed.');}};
 return <div className="settings-page"><section className="settings-panel panel"><h1>Settings</h1><label>UI scale<select value={scale} onChange={(e)=>{const next=Number(e.target.value);setScale(next);localStorage.setItem('lynesque-ui-scale',String(next));document.documentElement.style.setProperty('--ui-scale',String(next));}}><option value="0.75">75%</option><option value="0.9">90%</option><option value="1">100%</option><option value="1.1">110%</option><option value="1.25">125%</option><option value="1.5">150%</option></select></label><label>Feed next/previous buttons<select value={arrowSide} onChange={(e)=>{const next=e.target.value==='right'?'right':'left';setArrowSide(next);localStorage.setItem('lynesque-arrow-side',next);}}><option value="left">Left of video</option><option value="right">Right of video</option></select></label><div className="settings-head"><h2>Notifications</h2><button onClick={()=>setReports(true)}>Reports</button></div>{preferences&&<div className="notification-options">{(Object.keys(labels) as NotificationKind[]).map((kind)=><label key={kind}><input type="checkbox" checked={preferences[kind]} onChange={(e)=>setPreferences({...preferences,[kind]:e.target.checked})}/><span>{labels[kind]}</span></label>)}</div>}<button className="primary" onClick={save}>Save notification options</button>{status&&<div className="status">{status}</div>}</section></div>;
}
