import { useEffect,useState } from 'react';
import { beginPatreonLink,currentUser,emojiUrl,getNotificationSettings,getPatreonStatus,refreshPatreonLink,requestEmailVerification,setEmojiBadge,setMatureContent,setMfa,setNotificationSettings,unlinkPatreon } from '../api';
import type { NotificationKind,NotificationPreferences,PatreonStatus,User } from '../types';
import { Reports } from './Reports';
import { saveTheme,themeSettings } from '../theme';
import { useCustomEmojis } from './CustomEmoji';

const labels:Record<NotificationKind,string>={post_like:'Someone likes your video',post_dislike:'Someone dislikes your video',follow:'Someone follows you',unfollow:'Someone unfollows you',comment_mention:'You are mentioned in a video comment',video_mention:'You are mentioned in video text or its title',comment:'Someone comments on your video',comment_like:'Someone likes your video comment',comment_dislike:'Someone dislikes your video comment',board_like:'Someone likes your Postboard post',board_dislike:'Someone dislikes your Postboard post',board_comment:'Someone comments on your Postboard post',board_mention:'You are mentioned in a Postboard post',board_comment_mention:'You are mentioned in a Postboard reply',board_comment_like:'Someone likes your Postboard reply',board_comment_dislike:'Someone dislikes your Postboard reply',follow_video:'Someone you follow posts a video',follow_board:'Someone you follow makes a Postboard post',following_video_comment:'Someone you follow comments on a video',following_board_comment:'Someone you follow comments on Postboard',asset_removed:'Your asset is taken down',content_removed:'Your content is taken down',content_mature:'A moderator changes the Mature tag on your video',board_content_mature:'A moderator changes the Mature tag on your Postboard post',admin_changed:'Your account or admin status changes',report_resolved:'Your report is accepted or denied',review_resolved:'Your reviewed upload is accepted or denied',admin_rate_limited:'An admin is automatically rate-limited',automatic_suspension:'A user is automatically suspended by asset safety'};

export function Settings({apiBase,token,user,onUserChanged,onLogout,onPolicies}:{apiBase:string;token:string;user:User;onUserChanged:(user:User)=>void;onLogout:()=>void;onPolicies:()=>void}){
 const [preferences,setPreferences]=useState<NotificationPreferences>();
 const [scale,setScale]=useState(Number(localStorage.getItem('lynesque-ui-scale')||1));
 const [arrowSide,setArrowSide]=useState(localStorage.getItem('lynesque-arrow-side')==='right'?'right':'left');
 const [reports,setReports]=useState(false);
 const [status,setStatus]=useState('');
 const [theme,setTheme]=useState(themeSettings);
 const [patreonStatus,setPatreonStatus]=useState<PatreonStatus>();
 const [patreonBusy,setPatreonBusy]=useState(false);
 const [email,setEmail]=useState(user.email||'');
 const [emailBusy,setEmailBusy]=useState(false);
 const [mfaPassword,setMfaPassword]=useState('');
 const [securityBusy,setSecurityBusy]=useState(false);
 const emojis=useCustomEmojis(apiBase);
 const loadPatreon=()=>getPatreonStatus(apiBase,token).then(setPatreonStatus);
 useEffect(()=>{getNotificationSettings(apiBase,token).then((r)=>setPreferences(r.preferences)).catch((e)=>setStatus(e.message));void loadPatreon().catch((e)=>setStatus(e.message));},[apiBase,token]);
 useEffect(()=>{const refresh=()=>currentUser(apiBase,token).then((result)=>{onUserChanged(result.user);setEmail(result.user.email||email);}).catch(()=>{});window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh);},[apiBase,token,email,onUserChanged]);
 if(reports)return <Reports apiBase={apiBase} token={token} user={user} onBack={()=>setReports(false)}/>;
 const save=async()=>{if(!preferences)return;try{setPreferences((await setNotificationSettings(apiBase,token,preferences)).preferences);setStatus('Notification options saved.');}catch(e){setStatus(e instanceof Error?e.message:'Save failed.');}};
 const connectPatreon=async()=>{const popup=window.open('about:blank','lynesque-patreon','popup,width=620,height=760');setPatreonBusy(true);setStatus('Opening Patreon…');try{const result=await beginPatreonLink(apiBase,token);if(popup)popup.location.href=result.authorizationUrl;else window.location.href=result.authorizationUrl;let attempts=0;const timer=window.setInterval(async()=>{attempts++;try{const next=await getPatreonStatus(apiBase,token);setPatreonStatus(next);if(next.linked){window.clearInterval(timer);setPatreonBusy(false);setStatus(next.entitled?'Patreon connected. Your account is verified.':'Patreon connected, but the eligible active membership was not found.');const refreshed=await refreshPatreonLink(apiBase,token).catch(()=>undefined);if(refreshed)onUserChanged(refreshed.user);if(popup&&!popup.closed)popup.close();}else if(attempts>=80||popup?.closed){window.clearInterval(timer);setPatreonBusy(false);setStatus(attempts>=80?'Patreon connection timed out. You can try again.':'Patreon connection was closed.');}}catch{}},1500);}catch(e){popup?.close();setPatreonBusy(false);setStatus(e instanceof Error?e.message:'Could not connect Patreon.');}};
 const checkPatreon=async()=>{setPatreonBusy(true);try{const result=await refreshPatreonLink(apiBase,token);onUserChanged(result.user);await loadPatreon();setStatus(result.entitled?'Your Patreon membership is active.':'The eligible active Patreon membership was not found.');}catch(e){setStatus(e instanceof Error?e.message:'Could not check Patreon.');}finally{setPatreonBusy(false);}};
 const disconnectPatreon=async()=>{if(!window.confirm('Disconnect Patreon from this Lynesque account? This does not cancel the Patreon membership.'))return;setPatreonBusy(true);try{const result=await unlinkPatreon(apiBase,token);onUserChanged(result.user);await loadPatreon();setStatus('Patreon disconnected. Your Patreon subscription was not cancelled.');}catch(e){setStatus(e instanceof Error?e.message:'Could not disconnect Patreon.');}finally{setPatreonBusy(false);}};
 const changeMfa=async()=>{if(!mfaPassword)return setStatus('Enter your current password to change MFA.');setSecurityBusy(true);try{const result=await setMfa(apiBase,token,!user.mfaEnabled,mfaPassword);onUserChanged(result.user);setMfaPassword('');setStatus(result.message);}catch(error){setStatus(error instanceof Error?error.message:'MFA change failed.');}finally{setSecurityBusy(false);}};
 const changeMature=async(enabled:boolean)=>{let confirmAdult=false;if(enabled&&!user.matureAgeConfirmed){confirmAdult=window.confirm('Mature-tagged content may contain sexual themes or non-graphic violence. Confirm that you are at least 18 to show it.');if(!confirmAdult)return;}try{onUserChanged((await setMatureContent(apiBase,token,enabled,confirmAdult)).user);setStatus(enabled?'Mature-tagged content will be shown.':'Mature-tagged content is hidden.');}catch(error){setStatus(error instanceof Error?error.message:'Mature-content setting failed.');}};
 return <div className="settings-page">
  {status&&<div className="settings-status status" role="status" aria-live="polite"><span>{status}</span><button aria-label="Dismiss notice" onClick={()=>setStatus('')}>×</button></div>}
  <section className="settings-panel panel"><h1>Settings</h1>
   <label>UI scale<select value={scale} onChange={(e)=>{const next=Number(e.target.value);setScale(next);localStorage.setItem('lynesque-ui-scale',String(next));document.documentElement.style.setProperty('--ui-scale',String(next));}}><option value="0.75">75%</option><option value="0.9">90%</option><option value="1">100%</option><option value="1.1">110%</option><option value="1.25">125%</option><option value="1.5">150%</option></select></label>
   <label>Feed next/previous buttons<select value={arrowSide} onChange={(e)=>{const next=e.target.value==='right'?'right':'left';setArrowSide(next);localStorage.setItem('lynesque-arrow-side',next);}}><option value="left">Left of video</option><option value="right">Right of video</option></select></label>
   <h2>Theme</h2><div className="theme-options"><label>Base color<input type="color" value={theme.base} onChange={(e)=>{const next={...theme,base:e.target.value};setTheme(next);saveTheme(next);}}/></label><label>Accent color<input type="color" value={theme.accent} onChange={(e)=>{const next={...theme,accent:e.target.value};setTheme(next);saveTheme(next);}}/></label><label>Text color<input type="color" value={theme.text} onChange={(e)=>{const next={...theme,text:e.target.value};setTheme(next);saveTheme(next);}}/></label><button onClick={()=>{const next={base:'#0c0c0e',accent:'#9485ff',text:'#f4f4f4'};setTheme(next);saveTheme(next);}}>Reset theme</button></div>
   <section className="email-settings"><div className="settings-head"><h2>Email and MFA</h2>{user.emailVerified&&<span className="patreon-active">Email verified</span>}</div><p>Each email address can belong to only one Lynesque account. A verified email can also protect sign-in with a one-time code.</p><form onSubmit={async(event)=>{event.preventDefault();setEmailBusy(true);try{const result=await requestEmailVerification(apiBase,token,email);if(result.user)onUserChanged(result.user);setStatus(result.alreadyVerified?'That email is already verified.':result.message||'Verification email sent.');}catch(error){setStatus(error instanceof Error?error.message:'Verification email failed.');}finally{setEmailBusy(false);}}}><input type="email" autoComplete="email" value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="you@example.com"/><button className="primary" disabled={emailBusy||!email.trim()}>{emailBusy?'Sending…':user.emailVerified&&email===user.email?'Verified':'Send verification link'}</button></form><div className="mfa-controls"><input type="password" autoComplete="current-password" value={mfaPassword} onChange={(event)=>setMfaPassword(event.target.value)} placeholder="Current password"/><button disabled={securityBusy||!user.emailVerified} onClick={()=>void changeMfa()}>{securityBusy?'Working…':user.mfaEnabled?'Disable email MFA':'Enable email MFA'}</button></div>{!user.emailVerified&&<small>Verify your email before enabling MFA.</small>}</section>
   <section className="mature-settings"><h2>Content visibility</h2><label className="check"><input type="checkbox" checked={Boolean(user.showMatureContent)} onChange={(event)=>void changeMature(event.target.checked)}/> Show posts tagged Mature</label><p>Mature content is hidden by default. It may include suggestive material or non-graphic violence, but the tag never permits pornography, realistic nudity, gore, or hate speech.</p></section>
   {user.isVerified&&<section className="emoji-badge-settings"><h2>Custom emoji badge</h2><p>Verified accounts can place one host custom emoji beside their name.</p><div className="emoji-badge-options"><button className={!user.customEmojiBadge?'active':''} onClick={async()=>onUserChanged((await setEmojiBadge(apiBase,token)).user)}>None</button>{emojis.map((name)=><button className={user.customEmojiBadge===name?'active':''} title={`:${name}:`} key={name} onClick={async()=>onUserChanged((await setEmojiBadge(apiBase,token,name)).user)}><img src={emojiUrl(apiBase,name)} alt={`:${name}:`}/></button>)}</div></section>}
   <section className="patreon-settings"><div className="settings-head"><h2>Patreon verification</h2>{patreonStatus?.entitled&&<span className="patreon-active">Active</span>}</div><p><a href="https://www.patreon.com/cw/Lynesque/membership" target="_blank" rel="noreferrer">View the Lynesque Patreon membership</a></p>{!patreonStatus&&<p>Checking Patreon configuration…</p>}{patreonStatus&&!patreonStatus.configured&&<p className="review-notice">Patreon linking is not ready on this host yet. {patreonStatus.error}</p>}{patreonStatus?.configured&&!patreonStatus.eligible&&<p className="review-notice">Unverified accounts cannot obtain verified status by subscribing. The moderation system must first move this account to Default status.</p>}{patreonStatus?.configured&&patreonStatus.eligible&&!patreonStatus.linked&&<><p>Connect the Patreon account subscribed to <strong>{patreonStatus.tierTitle||'the $5 tier'}</strong>.</p><button className="primary" disabled={patreonBusy} onClick={()=>void connectPatreon()}>{patreonBusy?'Connecting…':'Link Patreon'}</button></>}{patreonStatus?.configured&&patreonStatus.linked&&<><p>{patreonStatus.entitled?'Your eligible Patreon membership is active, so this account receives verified status.':'Patreon is linked, but the eligible membership is not currently active.'}</p>{patreonStatus.lastCheckedAt&&<small>Last checked {new Date(patreonStatus.lastCheckedAt).toLocaleString()}</small>}<div className="patreon-actions"><button disabled={patreonBusy} onClick={()=>void checkPatreon()}>Check membership</button><button disabled={patreonBusy} onClick={()=>void disconnectPatreon()}>Disconnect</button></div></>}{patreonStatus?.configured&&!patreonStatus.webhookConfigured&&<small className="patreon-warning">Automatic changes are not active until the host configures the Patreon webhook secret.</small>}</section>
   <div className="settings-head"><h2>Notifications</h2><button onClick={()=>setReports(true)}>Reports</button></div>{preferences&&<div className="notification-options">{(Object.keys(labels) as NotificationKind[]).map((kind)=><label key={kind}><input type="checkbox" checked={preferences[kind]} onChange={(e)=>setPreferences({...preferences,[kind]:e.target.checked})}/><span>{labels[kind]}</span></label>)}</div>}<button className="primary" onClick={save}>Save notification options</button>
   <section className="account-actions"><h2>Account and policies</h2><div><button onClick={onPolicies}>Privacy, Terms, Rules, age, and takedowns</button><button className="danger" onClick={onLogout}>Log out</button></div></section>
  </section>
 </div>;
}
